### ISSUE TITLE
Definir tempos de cortes de todas as atividades do evento

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2021-org#293]
### Descrição
Na transmissão das palestras, durante a Python Brasil, foi criado um stream por trilha e por dia (com algumas exceções). Isso resultou em vídeos no YouTube, contendo múltiplas palestras. Keynotes e palestras relâmpago também estão juntas nos mesmo vídeos. Já as mesas redondas, foram feitas sozinhas, porém, ainda é possível ver partes no início e fim que podem ser cortados.

Para que publiquemos vídeos específicos de cada uma das atividades , é preciso:
1) Baixar os vídeos originais de todas as transmissões
2) Assistir o começo e o fim de todas as atividades no vídeo
3) Anotar o segundo que cada uma das atividades começam e terminam

### Como ajudar

1) Escolha uma das issues das trilhas/dia abaixo que ainda não tem responsável.
2) Comente na issue específica `Quero ajudar` que nós mandaremos o link para do vídeo para download
2) Assista ao vídeo e anote os tempos. A palestra começa no momento em que a pessoa *host* começa a falar (nesse tempo pode incluir comentários e recados do evento) **atenção ao keynotes, vídeo de patrocinadores devem ser cortados**. Já o final, deve ser considerando o momento em que a pessoa host e palestrante se despedem. **Dica**: com o tocador de mídias [VLC](https://www.videolan.org/) é rápido e fácil de pular para cenas específicas do vídeo.
4) Submeta um pull request para o [repositório das atividades](https://github.com/rougeth/calendaryo/tree/master/conferencias/python-brazil-2021), com o início, fim e nome do arquivo usado.

Exemplo:

Supondo que você deseja trabalhar na issue do dia 10/12, trilha Marie Van Brittan Brown. Após baixar o arquivo do vídeo e anotar os tempos das palestras, vá até o arquivo [palestras.toml](https://github.com/rougeth/calendaryo/blob/master/conferencias/python-brazil-2021/palestras.toml). Lá você encontrará a descrição de todas as palestras, como por exemplo:

```toml
[[slot]]
type = "talk"
author = "Andrews Medina"
minibio = "Andrews Medina é um software developer, co-creator do tsuru.io e do splinter, e tem experiência liderando times de desenvolvimento e tecnologia. No passado fez parte do time de tecnologia da Globo.com e do Jusbrasil. Atualmente trabalha liderando o time de tecnologia do Indaband."
description = "Nessa palestra vamos entender porque analisar áudio é diferente dos dados textuais. Como podemos utilizar Python para extrair features, analisar áudios e quais problemas podemos resolver com isso."
name = "Analisando e processando sinais de áudio em Python"
start_at = 2021-10-12T15:50:00-03:00
duration = 45
discord_channel = "893958335383089223"
room = "Marie Van Brittan Brown"
youtube_channel = "https://youtu.be/SU7H9Qbj8R4"
```

Uma vez com os tempos, adicione em cada uma das palestras do seu dia/trilha, o tempo de começo e fim e o nome do arquivo usado:

```diff
[[slot]]
type = "talk"
author = "Andrews Medina"
minibio = "Andrews Medina é um software developer, co-creator do tsuru.io e do splinter, e tem experiência liderando times de desenvolvimento e tecnologia. No passado fez parte do time de tecnologia da Globo.com e do Jusbrasil. Atualmente trabalha liderando o time de tecnologia do Indaband."
description = "Nessa palestra vamos entender porque analisar áudio é diferente dos dados textuais. Como podemos utilizar Python para extrair features, analisar áudios e quais problemas podemos resolver com isso."
name = "Analisando e processando sinais de áudio em Python"
start_at = 2021-10-12T15:50:00-03:00
duration = 45
discord_channel = "893958335383089223"
room = "Marie Van Brittan Brown"
youtube_channel = "https://youtu.be/SU7H9Qbj8R4"
+    [slot.stream]
+    start_at = 123  # Em que segundo do vídeo a palestra começa
+    end_at = 456  # Em que segundo do vídeo a palestra termina
+    filename = "pybr2021_algorave_pythonbrasil__20211015_220658.mp4"  # Nome do arquivo da palestra
```

Com todas as palestras finalizadas, faça um PR para o repositório.

### Tarefas
- Segunda-feira
  - [x] Definir tempos de corte: 10/11 - Marie Van Brittan Brown
  - [x] Definir tempos de corte: 10/11 - Angelica Ross
  - [x] Definir tempos de corte: 10/11 - Timnit Gebru
  - [x] Definir tempos de corte: 10/11 - Bonnie Prado Pinto
  - [x] Definir tempos de corte: 10/11 - Shirley Ann Jackson
  - [x] Definir tempos de corte: 10/11 - Mesa redonda, Palestra relâmpago e Keynote
- Terça-feira
  - [x] #294 (@jtemporal)
  - [x] #295 (@jtemporal)
  - [x] #296 (@jtemporal)
  - [x] #297 (@jtemporal)
  - [x] #298 (@jtemporal)
  - [x] #299 (@jtemporal)
- Quarta-feira
  - [x] #300 (@GabrielRF)
  - [x] #301 (@GabrielRF)
  - [x] #302 (@mhadaniya)
  - [x] #303 (@tiagobpires)
  - [x] #304 (@muriloviana)
  - [x] #305 (@muriloviana)
- Quinta-feira
  - [x] #306 (@russianbb)
  - [x] #307 (@russianbb)
  - [x] #308 (@russianbb)
  - [x] #309 (@russianbb)
  - [x] #310 (@camont1)
  - [x] #311 (@gabubellon)
- Sexta-feira
  - [x] #312 (@camont1)
  - [x] #313 (@muriloviana)
  - [x] #314 (@camont1)
  - [x] #315 (@liviocunha)
  - [x] #316 (@liviocunha)
  - [x] #317 (@muriloviana)
