### ISSUE TITLE
Definir estrutura do arquivo fonte dos dados do evento

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2021-org#94]
# Descrição
Para facilitar a manutenção da grade de palestrantes na Python Brasil 2019, eu criei um script que gerava um calendário (e a grade) a partir de arquivos  estáticos hospedados no Github. Isso facilitou fazermos mudanças antes e durante o evento, já que os organizadores já estavam familiarizados com Github. Para fazer qualquer mudança, bastava um *pull request* e a atualização era refletida na grade no site e nos calendários das pessoas.

Durante a edição dos vídeos da Python Brasil 2020, vimos que esses arquivos seriam muito úteis para automatizarmos outros processos da organização, como criação das artes das palestras para divulgação nas redes sociais. Exemplo do [arquivo fonte](https://github.com/rougeth/calendaryo/blob/master/conferencias/python-brazil-2020/palestras.toml) com dados das palestras da Python Brasil 2020.

Objetivo dessa issue é **definirmos a estrutura dos arquivos fonte dos dados da Python Brasil 2021**.

### Proposta

- Formado do arquivo: TOML
	- https://toml.io/
	- TOML tenta ser um formato de arquivo de configuração simples e de fácil leitura
- Para melhorar legibilidade, os dados podem ser divididos em múltiplos arquivos em múltiplas pastas.
- Os arquivos devem ter informações suficientes para:
	- Automatizar edição e publicação dos vídeos no YouTube
	- Automatizar criação das artes de divulgação das palestras com fotos dos participantes
	- Automatizar criação e atualização do calendário/grade de palestras no site
	- Manter histórico das atividades do evento

```TOML
[event]
name = "Python Brasil 2021"
slug = "pybr2021"
tags = ["pybr2021", "pybr21", "pybr"]  # TODO: onde será usado?
start_date = "2021-10-11"
end_date = "2021-10-17"

# [meta] pode ser usado para quaisquer informações comuns
# a todos os items de uma seção. Por exemplo, url do vídeo
# de abertura que deve ser adicionado nas palestras e o
# prefixo no título do vídeo no youtube
[meta.streaming]
opening_video_url = ""
youtube_title_prefix = "[PyBR2021]"

# Teríamos uma lista `[[atividade]]` para cada atividade do
# evento, como palestras, keynotes, sprints, etc.
[[activity]]
type = "talk"
title = "Título da palestra"
description = """
Descrição da palestra.
"""
date = 2021-11-01
start = 10:00:00
# TODO: O que é melhor:
# 1) Salvar a duranção da palestra ou
# 2) Salvar o horário exato em que ela termina
duration = 45
end = 10:45:00
room = "PEP404"
tags = ["iniciante", "ciência de dados", "pandas"]
urls = ["http://slides", "http://artigo"]

    [[activity.speaker]]
    first_name = "Marco"
    last_name = "Rougeth"
    website = ""
    social_network_urls = []
    photo_url = "https://localhost/photo.jpg"

    [[activity.streaming]]
    # Link para arquivo fonte da palestra no S3
    source_url = "https://s3.localhost/photo.jpg"
    start = 256  # Em segundos
    # TODO: duração ou tempo exato do corte final/
    end = 2048
```

<details>
  <summary>Histórico de revisões</summary>

- 06/27
  - Inclusão da seção `[event]` com informações do evento.
  - `[[activity]]` no lugar de `[[talk]]`
  - `[[activity.urls]]` links úteis
</details>

### Dúvidas
- Podemos validar se o arquivo está formatado corretamente, mas faz sentido validar os dados? Se sim, como?
- Estrutura dos tutoriais e sprints seriam semelhantes a estrutra das palestras, mas é preciso definí-las também.
- `TODO`s no exemplo.

Obs: Examplo esta em inglês por força do hábito, a língua não faz parte da proposta.
